version: "3"

services: 

# PHP Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

# Webserver
  web:
    build:
        context: ./
        dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8080:80

# Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=queue"
      - "MYSQL_USER=csab"
      - "MYSQL_PASSWORD=MDU8Qd7dffJdAwNeaSmgmr397y9dJy5"
      - "MYSQL_ROOT_PASSWORD=sWScf82k3nc9P8DavgZ6wGrDJjY9DMG"
    ports:
      - "33061:3306"

# Volumes
volumes:
  dbdata: