version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: laravel-queue-app
    container_name: queue-backend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - "6001:6001"
    depends_on:
      - redis
      - mysql
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
    networks:
      - app-network


  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - app-network

  #MySQL Service
  mysql:
    image: mysql:5.7
    container_name: laravel-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: queue
      MYSQL_ROOT_PASSWORD: csabqueuedbpassword1234
      MYSQL_USER: csab
      MYSQL_PASSWORD: csabqueuemysqlsecretpassword12345
    networks:
      - app-network

  #Redis Service
  redis:
    container_name: laravel-redis
    image: redis:4-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - app-network
  
  

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"